//! Compile-time generator of the CLI command-tier table.
//!
//! Reads `v1-surface-contract.toml` at build time and emits
//! `$OUT_DIR/command_tiers.rs` with a static slice mapping
//! `cli_command` → `(deployment_tier, required_plan)`.
//!
//! The generated table is consumed by `src/main.rs` via `include!()`. A
//! module-level test walks the clap command tree and asserts every leaf
//! subcommand has a row in the table (with a small skip-list for local /
//! operator commands that don't map to `/v1`).
//!
//! Gap-tracker: ENS-58 / CLI-TIER-003.

use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

const CONTRACT_PATH: &str = "v1-surface-contract.toml";

#[derive(Debug, Deserialize)]
struct Contract {
    endpoint: Vec<Endpoint>,
}

#[derive(Debug, Deserialize)]
struct Endpoint {
    #[allow(dead_code)]
    method: String,
    #[allow(dead_code)]
    path: String,
    cli_command: String,
    #[allow(dead_code)]
    status: String,
    #[serde(default)]
    #[allow(dead_code)]
    reason: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    note: Option<String>,
    deployment_tier: String,
    required_plan: String,
}

fn main() {
    println!("cargo:rerun-if-changed={}", CONTRACT_PATH);
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-env=CLI_TARGET={}", std::env::var("TARGET").unwrap());

    let toml_src = fs::read_to_string(CONTRACT_PATH)
        .unwrap_or_else(|e| panic!("build.rs: read {}: {}", CONTRACT_PATH, e));

    let contract: Contract = toml::from_str(&toml_src)
        .unwrap_or_else(|e| panic!("build.rs: parse {}: {}", CONTRACT_PATH, e));

    // Deduplicate on cli_command (the contract can list the same CLI command
    // for multiple HTTP endpoints, e.g. "collections update"). Take the first
    // occurrence for determinism — tier/plan are expected to match across
    // duplicates, but if they don't, the contract's own coherence tests are
    // the right place to catch it.
    let mut rows: Vec<(String, String, String)> = Vec::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    for e in contract.endpoint {
        if seen.insert(e.cli_command.clone()) {
            rows.push((e.cli_command, e.deployment_tier, e.required_plan));
        }
    }

    // Sort by cli_command for determinism / reproducible builds.
    rows.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from v1-surface-contract.toml. DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str("// Each row is (cli_command, deployment_tier, required_plan).\n");
    out.push_str("//   deployment_tier: \"any-mode\" | \"managed-only\"\n");
    out.push_str("//   required_plan:   \"free\" | \"professional\" | \"enterprise\"\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub static COMMAND_TIERS: &[(&str, &str, &str)] = &[\n");
    for (cmd, tier, plan) in &rows {
        out.push_str(&format!(
            "    ({:?}, {:?}, {:?}),\n",
            cmd, tier, plan
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set by cargo");
    let out_path = PathBuf::from(out_dir).join("command_tiers.rs");
    fs::write(&out_path, out)
        .unwrap_or_else(|e| panic!("build.rs: write {}: {}", out_path.display(), e));
}
