//! Pre-flight tier gating — ENS-61 / CLI-TIER-006.
//!
//! `preflight_gate` is called at the top of dispatch (after arg parse and
//! profile load, BEFORE any HTTP client construction) to short-circuit commands
//! the caller cannot run given their deployment mode or plan tier.
//!
//! The tier table (`COMMAND_TIERS`) is generated by `build.rs` from
//! `v1-surface-contract.toml` and lives in the `main` crate scope. It is
//! passed in as a `&'static [(&'static str, &'static str, &'static str)]`
//! parameter so this module stays decoupled from the generated include.

use crate::output::FailureClass;

/// Pre-flight gate result.
///
/// `Ok(())` means the command may proceed.
/// `Err(FailureClass)` means the command should be rejected before any
/// network activity with the specified failure class.
pub fn preflight_gate(
    cmd_key: &str,
    deployment_mode: &str,
    // "free" | "professional" | "enterprise" | None (unknown — proceed, let server be
    // authoritative).
    cached_plan: Option<&str>,
    tiers: &[(&str, &str, &str)],
) -> Result<(), FailureClass> {
    // Look up the command in the tier table.
    let row = tiers.iter().find(|(cmd, _, _)| *cmd == cmd_key);
    let (deployment_tier, required_plan) = match row {
        Some((_, dt, rp)) => (*dt, *rp),
        None => {
            // Command not in tier table → no gating (local/operator command).
            return Ok(());
        }
    };

    // Deployment-mode gate.
    if deployment_tier == "managed-only" && deployment_mode != "managed" {
        return Err(FailureClass::UnsupportedInLocalMode);
    }

    // Plan gate — only if we have a cached plan and the command requires one.
    if let Some(plan) = cached_plan {
        let plan_rank = plan_to_rank(plan);
        let required_rank = plan_to_rank(required_plan);
        if plan_rank < required_rank {
            return Err(FailureClass::PlanRequired);
        }
    }
    // No cached plan → proceed (server is authoritative).
    // TODO: if the server returns a plan hint header, cache it in profiles.toml.

    Ok(())
}

/// Numeric rank for plan tiers. Higher = more capability.
fn plan_to_rank(plan: &str) -> u8 {
    match plan {
        "free" => 0,
        "professional" => 1,
        "enterprise" => 2,
        _ => 0, // unknown plans don't upgrade the rank
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_TIERS: &[(&str, &str, &str)] = &[
        ("search", "any-mode", "free"),
        ("voices list", "any-mode", "free"),
        ("voices compare", "any-mode", "professional"),
        ("logs stream", "managed-only", "professional"),
        ("export tenant", "managed-only", "enterprise"),
    ];

    #[test]
    fn free_local_hitting_pro_command_returns_plan_required() {
        let result = preflight_gate("voices compare", "local", Some("free"), SAMPLE_TIERS);
        assert_eq!(result, Err(FailureClass::PlanRequired));
    }

    #[test]
    fn free_local_hitting_free_command_passes() {
        let result = preflight_gate("search", "local", Some("free"), SAMPLE_TIERS);
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn managed_only_against_local_returns_unsupported_in_local_mode() {
        let result = preflight_gate("logs stream", "local", Some("professional"), SAMPLE_TIERS);
        assert_eq!(result, Err(FailureClass::UnsupportedInLocalMode));
    }

    #[test]
    fn managed_only_against_managed_with_correct_plan_passes() {
        let result = preflight_gate("logs stream", "managed", Some("professional"), SAMPLE_TIERS);
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn managed_only_against_managed_insufficient_plan_returns_plan_required() {
        let result = preflight_gate("export tenant", "managed", Some("professional"), SAMPLE_TIERS);
        assert_eq!(result, Err(FailureClass::PlanRequired));
    }

    #[test]
    fn no_cached_plan_proceeds_to_wire() {
        // When cached_plan is None, the gate must pass (server is authoritative).
        let result = preflight_gate("voices compare", "local", None, SAMPLE_TIERS);
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn unknown_command_passes() {
        let result = preflight_gate("local-only-command", "local", Some("free"), SAMPLE_TIERS);
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn pro_plan_passes_pro_command() {
        let result = preflight_gate("voices compare", "local", Some("professional"), SAMPLE_TIERS);
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn enterprise_plan_passes_pro_command() {
        // Enterprise rank is higher than professional.
        let result = preflight_gate("voices compare", "local", Some("enterprise"), SAMPLE_TIERS);
        assert_eq!(result, Ok(()));
    }
}
